import os
import json
from dotenv import load_dotenv
from typing import TypedDict, Literal, List, Optional

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt

load_dotenv()

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_NAME  = "llama-3.3-70b-versatile"
TEMPERATURE = 0.7
MAX_TOKENS      = 1000
ALPHA_CORRECT   = 0.25
ALPHA_INCORRECT = 0.10
LEVEL_MIN       = 0.05
LEVEL_MAX       = 0.95
 
 
def _get_llm() -> ChatGroq:
  return ChatGroq(
    model=MODEL_NAME,
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=TEMPERATURE,
  )


# __ State shared by the agents ___________________________________________

class AgentState(TypedDict):
  """
  A single state shared between the three agents and the LangGraph workflow.

  Lifecycle:
    user_message → [RAG] → context → [Router] → intent
      → [ExerciseAgent] : current_exercise
      → [CorrectionAgent] : correction
      → [FeedbackAgent] : response
  """
 
  # ── Session ───────────────────────────────────────────────────────────────
  session_id      : str
  collection_name : str          # Collection ChromaDB for this session

  # ── User input ────────────────────────────────────────────────────
  user_message    : str

  # ── Profil apprenant ──────────────────────────────────────────────────────
  student_level   : float        # 0.0 → 1.0
  history         : list[dict]   # History for last exercises

  # ── RAG ───────────────────────────────────────────────────────────────────
  context         : list[str]    # Chunks got from the vector store

  # ── Exercise stream ─────────────────────────────────────────────────────────
  current_exercise : dict | None
  # Format :
  # {
  #   "question"        : str,
  #   "expected_answer" : str,
  #   "hints"           : list[str]   # optionnal
  # }
  student_answer   : str | None

  # ── Agents output ────────────────────────────────────────────────────
  correction : dict | None
  # Format attendu :
  # {
  #   "is_correct"     : bool,
  #   "score"          : float,        # 0.0 → 1.0
  #   "errors"         : list[str],
  #   "feedback_hints" : list[str]
  # }

  response   : str | None          # Final pedagogical response (FeedbackAgent)

  # ── Routing ───────────────────────────────────────────────────────────────
  intent : Literal["question", "exercise", "answer"] | None

  # ── Update level (generated by CorrectionAgent) ───────────────────
  updated_level : float | None


# __ FeedbacksAgent ____________________________________________________________

# ── Prompts ───────────────────────────────────────────────────────────────────
_PROMPT_TEMPLATE = """Tu es un tuteur pédagogique expert et bienveillant.
 
DOCUMENTS DE RÉFÉRENCE :
{context}
 
QUESTION DE L'ÉLÈVE :
{question}
 
{correction_info}
 
INSTRUCTIONS :
- Réponds en te basant UNIQUEMENT sur les documents fournis
- Explique de manière claire et pédagogique
- Utilise des exemples si nécessaire
- Encourage l'élève
- Si tu ne trouves pas l'information dans les documents, dis-le honnêtement
 
RÉPONSE :"""
 
 
# ── Public function ─────────────────────────────────────────────────────────
def generate_feedback(
  question: str,
  context: list[str],
  correction: dict | None = None,
) -> str:
  """
  Génère une réponse pédagogique pour une question d'étudiant.

  Args:
    question   : La question posée par l'étudiant.
    context    : Liste de chunks RAG pertinents.
    correction : Optionnel — résultat de CorrectionAgent :
      {
        "is_correct"     : bool,
        "score"          : float,
        "errors"         : list[str],
        "feedback_hints" : list[str]
      }

  Returns:
    Réponse pédagogique sous forme de string.
  """
  context_text = "\n\n".join(context) if context else "Aucun document fourni."

  correction_info = ""
  if correction:
    errors  = ", ".join(correction.get("errors", [])) or "Aucune"
    hints   = ", ".join(correction.get("feedback_hints", [])) or "Aucun"
    correction_info = (
      f"RÉSULTAT DE L'EXERCICE PRÉCÉDENT :\n"
      f"- Correct : {correction.get('is_correct', 'N/A')}\n"
      f"- Score   : {correction.get('score', 'N/A')}\n"
      f"- Erreurs : {errors}\n"
      f"- Pistes  : {hints}\n\n"
      f"Prends en compte ce résultat pour aider l'élève à comprendre ses erreurs."
    )

  prompt = ChatPromptTemplate.from_template(_PROMPT_TEMPLATE)
  chain  = prompt | _get_llm()

  response = chain.invoke({
    "question"       : question,
    "context"        : context_text,
    "correction_info": correction_info,
  })

  return response.content


# __ Exercise agent ____________________________________________________________

# ── Configuration ─────────────────────────────────────────────────────────────
_DIFFICULTY_MAP = {
  "easy"   : "Débutant — questions simples de mémorisation et compréhension",
  "medium" : "Intermédiaire — questions d'application et d'analyse",
  "hard"   : "Avancé — questions de synthèse et résolution de problèmes complexes",
}

# ── Prompt ────────────────────────────────────────────────────────────────────
_PROMPT_TEMPLATE = ChatPromptTemplate.from_messages([
  ("system", (
    "Tu es un Agent Générateur d'Exercices expert et pédagogue.\n"
    "Génère des exercices en français, parfaitement adaptés aux consignes.\n\n"
    "CONTEXTE DU COURS :\n{context}\n\n"
    "PROFIL DE L'APPRENANT :\n{learner_profile}\n"
  )),
  ("human", (
    "Génère UN exercice sur le sujet : {topic}\n"
    "Niveau de difficulté : {difficulty_label}\n\n"
    "Réponds UNIQUEMENT en JSON valide, sans texte autour, sans balises markdown :\n"
    "{{\n"
    "  \"question\"        : \"<énoncé complet de la question>\",\n"
    "  \"expected_answer\" : \"<réponse attendue détaillée>\",\n"
    "  \"hints\"           : [\"<indice 1>\", \"<indice 2>\"]\n"
    "}}"
  )),
])
 
 
# ── Public function ─────────────────────────────────────────────────────────
def generate_exercise(
  topic         : str,
  difficulty    : str = "medium",
  context       : list[str] | None = None,
  student_level : float = 0.5,
  history       : list[dict] | None = None,
) -> dict:
  """
  Génère un exercice adapté au sujet et au niveau de l'étudiant.

  Args:
    topic         : Sujet de l'exercice (ex: "les dérivées", "la récursivité").
    difficulty    : "easy" | "medium" | "hard".
    context       : Liste de chunks RAG pertinents (optionnel).
    student_level : Niveau de l'étudiant entre 0.0 et 1.0.
    history       : Historique des derniers exercices de l'étudiant (optionnel).

  Returns:
    {
      "question"        : str,
      "expected_answer" : str,
      "hints"           : list[str]
    }
  """
  context_text = "\n\n".join(context) if context else (
    "Pas de support spécifique fourni. Utilise tes connaissances générales."
  )

  difficulty_label = _DIFFICULTY_MAP.get(difficulty, _DIFFICULTY_MAP["medium"])

  learner_profile = f"Niveau actuel : {student_level:.2f} / 1.00\n"
  if history:
    last = history[-3:]
    learner_profile += f"Derniers exercices : {last}"
  else:
    learner_profile += "Aucun historique disponible."

  chain = _PROMPT_TEMPLATE | _get_llm() | StrOutputParser()

  raw = chain.invoke({
    "topic"           : topic,
    "difficulty_label": difficulty_label,
    "context"         : context_text,
    "learner_profile" : learner_profile,
  })

  # Cleaning and JSON parsing
  raw = raw.strip()
  if raw.startswith("```"):
    parts = raw.split("```")
    raw   = parts[1] if len(parts) > 1 else raw
    if raw.startswith("json"):
      raw = raw[4:]
  raw = raw.strip()

  exercise = json.loads(raw)

  # Guarantee of required fields
  exercise.setdefault("question",        "")
  exercise.setdefault("expected_answer", "")
  exercise.setdefault("hints",           [])

  return exercise


# __ Correction agent _________________________________________________________

class _CorrectionState(TypedDict):
    # Entrées
    exercise       : dict          # {question, expected_answer, hints}
    student_answer : str
    sources        : List[str]     # Chunks RAG bruts
    student_level  : float
 
    # Intermédiaires
    formatted_context   : str
    llm_inferred_answer : str
 
    # Sorties
    correction_result   : dict
    identified_gaps     : List[str]
    updated_level       : float
    correction_reasoning: str
 
    # HITL
    needs_human_review : bool
    human_feedback     : Optional[str]
 
 
# ── Prompts ───────────────────────────────────────────────────────────────────
_INFER_PROMPT = ChatPromptTemplate.from_messages([
  ("system", (
    "Tu es un expert pédagogique.\n"
    "On te donne une question et des extraits de cours.\n"
    "Ton rôle : lire les sources et déterminer quelle est la bonne réponse.\n\n"
    "Réponds UNIQUEMENT avec la bonne réponse attendue, en une phrase courte."
  )),
  ("human", (
    "## Question\n{question}\n\n"
    "## Sources du cours\n{formatted_context}\n\n"
    "Quelle est la réponse correcte à cette question ?"
  )),
])
 
_GAP_ANALYSIS_PROMPT = ChatPromptTemplate.from_messages([
  ("system", (
    "Tu es un analyste pédagogique expert.\n"
    "Un étudiant vient de répondre incorrectement à une question.\n"
    "Ton rôle : identifier POURQUOI il s'est trompé "
    "en te basant STRICTEMENT sur les sources du cours fournies.\n\n"
    "Réponds UNIQUEMENT en JSON valide, sans texte autour, sans balises markdown :\n"
    "{{\n"
    "  \"likely_misconception\" : \"<idée fausse probable de l'étudiant>\",\n"
    "  \"gaps\"                 : [\"<concept non maîtrisé 1>\", \"<concept 2>\"],\n"
    "  \"distractor_analysis\"  : \"<pourquoi cette réponse erronée semblait plausible>\",\n"
    "  \"feedback_hints\"       : [\"<conseil concret 1>\", \"<conseil 2>\"]\n"
    "}}"
  )),
  ("human", (
    "## Question\n{question}\n\n"
    "## Réponse attendue\n{expected_answer}\n\n"
    "## Réponse de l'étudiant\n{student_answer}\n\n"
    "## Sources du cours\n{formatted_context}\n\n"
    "Analyse l'erreur de l'étudiant."
  )),
])
 
 
# ── Nœuds du graphe ───────────────────────────────────────────────────────────
def _retrieve_node(state: _CorrectionState) -> _CorrectionState:
  """Formate les sources RAG en contexte textuel."""
  sources = state.get("sources", [])
  if not sources:
    state["formatted_context"] = "Aucune source disponible."
    return state

  state["formatted_context"] = "\n\n".join(
    f"[Source {i+1}]\n{chunk}" for i, chunk in enumerate(sources)
  )
  return state
 
 
def _infer_answer_node(state: _CorrectionState) -> _CorrectionState:
  """Demande au LLM de confirmer/inférer la bonne réponse depuis les sources."""
  llm = _get_llm()
  chain = _INFER_PROMPT | llm
  response = chain.invoke({
    "question"         : state["exercise"].get("question", ""),
    "formatted_context": state["formatted_context"],
  })
  state["llm_inferred_answer"] = response.content.strip()
  return state
 
 
def _mcq_check_node(state: _CorrectionState) -> _CorrectionState:
  """Correction déterministe : compare la réponse étudiant à la réponse attendue."""
  student = state["student_answer"].strip()
  expected = state["exercise"].get("expected_answer", "")
  inferred = state.get("llm_inferred_answer", expected)

  # Pour les QCM (réponse = une lettre), comparaison directe
  # Pour les questions ouvertes, on s'appuie sur llm_inferred_answer
  is_single_letter = len(student) == 1 and student.upper() in "ABCD"
  if is_single_letter:
      # Cherche si la lettre étudiant correspond à l'un des choix de la réponse attendue
      correct_letter = expected.strip().upper()[:1] if len(expected.strip()) == 1 else ""
      is_correct  = student.upper() == correct_letter if correct_letter else False
      valid_choice = True
  else:
      # Réponse ouverte : délègue au gap_analysis (score 0 par défaut ici,
      # réel évalué par le LLM dans gap_analysis)
      is_correct   = False
      valid_choice = bool(student)  # invalide seulement si vide

  state["correction_result"] = {
      "score"          : 1.0 if is_correct else 0.0,
      "verdict"        : "correct" if is_correct else "incorrect",
      "is_correct"     : is_correct,
      "student_answer" : student,
      "expected_answer": expected,
      "valid_choice"   : valid_choice,
      "ambiguous"      : False,
  }
  return state
 
 
def _ambiguity_check(state: _CorrectionState) -> str:
    """Routeur : réponse vide/invalide → HITL, sinon → gap_analysis."""
    if not state["correction_result"].get("valid_choice", True):
        state["needs_human_review"] = True
        return "hitl"
    state["needs_human_review"] = False
    return "gap_analysis"
 
 
def _hitl_node(state: _CorrectionState) -> _CorrectionState:
    """Suspend l'exécution pour intervention humaine sur réponse invalide."""
    human_input = interrupt({
        "message"       : "Réponse invalide — révision humaine requise",
        "question"      : state["exercise"].get("question", ""),
        "student_answer": state["student_answer"],
    })
 
    if human_input:
        state["human_feedback"] = human_input.get("comment", "")
        if "score" in human_input:
            score = float(human_input["score"])
            state["correction_result"]["score"]      = score
            state["correction_result"]["is_correct"] = score >= 0.5
            state["correction_result"]["verdict"]    = "correct" if score >= 0.5 else "incorrect"
        if "gaps" in human_input:
            state["identified_gaps"] = human_input["gaps"]
 
    return state
 
 
def _gap_analysis_node(state: _CorrectionState) -> _CorrectionState:
    """Analyse LLM des lacunes (uniquement si réponse incorrecte)."""
    result = state["correction_result"]
 
    if result["is_correct"]:
        state["identified_gaps"]      = []
        state["correction_reasoning"] = "Réponse correcte."
        return state
 
    llm   = _get_llm()
    chain = _GAP_ANALYSIS_PROMPT | llm
    response = chain.invoke({
        "question"         : state["exercise"].get("question", ""),
        "expected_answer"  : state["exercise"].get("expected_answer", ""),
        "student_answer"   : state["student_answer"],
        "formatted_context": state["formatted_context"],
    })
 
    raw = response.content.strip()
    if raw.startswith("```"):
        parts = raw.split("```")
        raw   = parts[1] if len(parts) > 1 else raw
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()
 
    try:
        analysis = json.loads(raw)
    except json.JSONDecodeError:
        analysis = {
            "likely_misconception": "Analyse non disponible.",
            "gaps"               : [],
            "distractor_analysis": "",
            "feedback_hints"     : [],
        }
 
    state["identified_gaps"]      = analysis.get("gaps", [])
    state["correction_reasoning"] = json.dumps(analysis, ensure_ascii=False)
 
    # Enrichit correction_result avec les hints pour le FeedbackAgent
    state["correction_result"]["feedback_hints"] = analysis.get("feedback_hints", [])
    state["correction_result"]["errors"]         = analysis.get("gaps", [])
 
    return state
 
 
def _update_level_node(state: _CorrectionState) -> _CorrectionState:
    """Recalcule le niveau de l'étudiant (moyenne mobile asymétrique)."""
    score          = state["correction_result"]["score"]
    previous_level = state.get("student_level", 0.5)
 
    alpha     = ALPHA_CORRECT if score == 1.0 else ALPHA_INCORRECT
    new_level = alpha * score + (1 - alpha) * previous_level
    new_level = round(max(LEVEL_MIN, min(LEVEL_MAX, new_level)), 3)
 
    state["updated_level"] = new_level
    return state
 
 
# ── Construction du graphe (singleton) ───────────────────────────────────────
def _build_graph():
    graph = StateGraph(_CorrectionState)
 
    graph.add_node("retrieve"    , _retrieve_node)
    graph.add_node("infer_answer", _infer_answer_node)
    graph.add_node("mcq_check"   , _mcq_check_node)
    graph.add_node("hitl"        , _hitl_node)
    graph.add_node("gap_analysis", _gap_analysis_node)
    graph.add_node("update_level", _update_level_node)
 
    graph.set_entry_point("retrieve")
    graph.add_edge("retrieve"    , "infer_answer")
    graph.add_edge("infer_answer", "mcq_check")
 
    graph.add_conditional_edges(
        "mcq_check",
        _ambiguity_check,
        {"hitl": "hitl", "gap_analysis": "gap_analysis"},
    )
 
    graph.add_edge("hitl"        , "gap_analysis")
    graph.add_edge("gap_analysis", "update_level")
    graph.add_edge("update_level", END)
 
    return graph.compile(
        checkpointer=MemorySaver(),
        interrupt_before=["hitl"],
    )
 
 
_correction_graph = _build_graph()
 
 
# ── Fonction publique ─────────────────────────────────────────────────────────
def correct_answer(
    exercise      : dict,
    student_answer: str,
    context       : list[str] | None = None,
    student_level : float = 0.5,
    session_id    : str = "default",
) -> dict:
    """
    Corrige la réponse d'un étudiant et retourne le résultat structuré.
 
    Args:
        exercise       : Dict produit par ExerciseAgent :
                         {question, expected_answer, hints}
        student_answer : Réponse libre de l'étudiant.
        context        : Chunks RAG pertinents (optionnel).
        student_level  : Niveau courant de l'étudiant (0.0 → 1.0).
        session_id     : Identifiant de session (pour le checkpointer HITL).
 
    Returns:
        {
            "is_correct"     : bool,
            "score"          : float,        # 0.0 → 1.0
            "errors"         : list[str],    # Lacunes identifiées
            "feedback_hints" : list[str],    # Conseils pour le FeedbackAgent
            "updated_level"  : float,        # Nouveau niveau calculé
            "verdict"        : str           # "correct" | "incorrect"
        }
    """
    initial_state: _CorrectionState = {
        "exercise"           : exercise,
        "student_answer"     : student_answer,
        "sources"            : context or [],
        "student_level"      : student_level,
        "formatted_context"  : "",
        "llm_inferred_answer": "",
        "correction_result"  : {},
        "identified_gaps"    : [],
        "updated_level"      : student_level,
        "correction_reasoning": "",
        "needs_human_review" : False,
        "human_feedback"     : None,
    }
 
    config = {"configurable": {"thread_id": session_id}}
    result = _correction_graph.invoke(initial_state, config=config)
 
    correction = result.get("correction_result", {})
    return {
        "is_correct"    : correction.get("is_correct", False),
        "score"         : correction.get("score", 0.0),
        "errors"        : result.get("identified_gaps", []),
        "feedback_hints": correction.get("feedback_hints", []),
        "updated_level" : result.get("updated_level", student_level),
        "verdict"       : correction.get("verdict", "incorrect"),
    }